# Generated by Django 3.0.4 on 2020-03-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('animal', models.CharField(max_length=20)),
                ('cant_animales', models.IntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('imagen', models.ImageField(default='imagenes/None/no-img.jpg', upload_to='imagenes/')),
            ],
        ),
    ]
