# Generated by Django 3.0.4 on 2020-03-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_auto_20200325_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='id',
            new_name='identificativo',
        ),
    ]
