# Generated by Django 3.0.4 on 2020-03-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_auto_20200325_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='id',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
