# Generated by Django 3.0.4 on 2020-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_datos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=400),
        ),
    ]
