# Generated by Django 3.0.4 on 2020-03-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_datos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='edad_animal',
            field=models.IntegerField(default=1),
        ),
    ]
