# Generated by Django 3.0.4 on 2020-03-25 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_datos_edad_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 22, 13, 31, 844128, tzinfo=utc)),
        ),
    ]
