# Generated by Django 2.2.2 on 2020-04-04 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_datos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 15, 16, 37, 584666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos',
            name='imagen',
            field=models.ImageField(default='imagenes/None/no-img.jpg', upload_to='images/'),
        ),
    ]
