# Generated by Django 2.2.2 on 2020-04-27 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_auto_20200426_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_adopcion',
            name='id',
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 0, 58, 6, 995116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 0, 58, 6, 997202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='numero_telefono_persona',
            field=models.IntegerField(default='0975209464'),
        ),
    ]
