# Generated by Django 2.2.2 on 2020-05-04 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_auto_20200502_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 1, 46, 48, 815705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 1, 46, 48, 817933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_extravio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 1, 46, 48, 819982, tzinfo=utc)),
        ),
    ]
