# Generated by Django 2.2.10 on 2020-05-25 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_auto_20200502_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 22, 37, 12, 920614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 22, 37, 12, 921116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_extravio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 22, 37, 12, 921583, tzinfo=utc)),
        ),
    ]
