# Generated by Django 2.2.10 on 2020-05-26 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0014_auto_20200525_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 1, 2, 4, 556050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 1, 2, 4, 556802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_adopcion',
            name='imagen',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='datos_extravio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 1, 2, 4, 557412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datos_extravio',
            name='imagen',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
