"""
Django settings for mapanimales project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

import platform

# for heroku deploy 



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1^h=@mepw)91b3r%5u2_%j7scsgfb93wn@oizk8yavr-44vfpg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mapp', 
    'social_django',
]

AUTHENTICATION_BACKENDS = (
  
   'social_core.backends.google.GoogleOAuth2',
   'django.contrib.auth.backends.ModelBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mapanimales.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mapanimales.wsgi.application'
TEMPLATE_CONTEXT_PROCESSORS = (
   'django.contrib.auth.context_processors.auth',
   'django.core.context_processors.debug',
   'django.core.context_processors.i18n',
   'django.core.context_processors.media',
   'django.core.context_processors.static',
   'django.core.context_processors.tz',
   'django.contrib.messages.context_processors.messages',
   'social.apps.django_app.context_processors.backends',
   'social.apps.django_app.context_processors.login_redirect',
)


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#here we have to change to deploy in heroku 
#para el config online, se deja este asi
plataforma=platform.platform() # sacamos el SO, heroku tiene en su descripcion aws,
# eso nos sirve para comprobar que esta corriendo en la nube
if plataforma.find('aws')>=0: # esta en la nube
    import dj_database_url  
    import dotenv
    DATABASES = {}
    DATABASES['default'] = dj_database_url.config()
    #static files
    STATICFILES_DIRS = []
    # (
    #       os.path.join(BASE_DIR, 'static'),
    #  )

    STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'


else:
    # this is for local deploy

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT  =   os.path.join(BASE_DIR, 'static') # esto es par el deploy en heroku 
STATIC_URL = '/static/'


MEDIA_ROOT =  os.path.join(BASE_DIR, 'media') 
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/inicio'

LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/auth/login/google-oauth2/'


SOCIAL_AUTH_URL_NAMESPACE = 'social'
#817360624013-at2a0rl9ncin77kvbdudsf88dbv1m8al.apps.googleusercontent.com
#F1EAJ1JaarfTose9FdUrmach
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '817360624013-at2a0rl9ncin77kvbdudsf88dbv1m8al.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'F1EAJ1JaarfTose9FdUrmach'

#https://dev.to/codetricity/how-to-set-up-django-with-central-oauth2-login-1co

